### ISSUE TITLE
Error while using toolbar-android with use_frameworks in podfile

### ISSUE THREAD

**Issue by Prince-Mittal** [react-native-toolbar-android/toolbar-android#19]
<img width="272" alt="Issue-1" src="https://user-images.githubusercontent.com/43432878/109288866-6e19d880-784b-11eb-8afa-a7fa26f0679e.png">
<img width="585" alt="Issue-11" src="https://user-images.githubusercontent.com/43432878/109288869-707c3280-784b-11eb-8a86-8855161138f6.png">

Xcode Version : 12.4
react-native version : 0.63.3
react version : 16.13.1
@react-native-community/toolbar-android version: "0.1.0-rc.2"

Podfile :
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

# Override Firebase SDK Version
# $FirebaseSDKVersion = '6.34.0'

# Allow iOS Static Frameworks
$RNFirebaseAsStaticFramework = true

target 'AppName' do
  config = use_native_modules!
  use_frameworks!
  # use_frameworks! :linkage => :static
  # use_frameworks! :linkage => :dynamic
  use_react_native!(:path => config["reactNativePath"])
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'BlinkReceipt'
  pod 'BlinkEReceipt'

  target 'AppNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

```
We want to use the android toolbar in the project which is using use_frameworks in podfile. But it is causing linking issues. We have tried to add framework in the build Phases but still we are getting the same problem. I have added the screenshots of the issue shown in the xcode. Can anybody help with this?

**Comment by RT-UpBeam** [comment]
Running into the same issue. Are you on an Apple Silicon chip?

**Comment by Prince-Mittal** [comment]
@super-potion I was running into this issue due to the usage of use_frameworks! according to which every pod should be dynamic frameworks but this was causing issue with the static libraries used in react-native project. So to use dynamic frameworks with static libraries I have found a plugin called `cocoapods-user-defined-build-types` that can be used to define the build type of every pod or any specific pod.
