### ISSUE TITLE
Makes building fail on react-native 0.65

### ISSUE THREAD

**Issue by Shywim** [react-native-toolbar-android/toolbar-android#51]
Hello 👋

React Native 0.65 bumped the fresco dependency from [2.3.0 to 2.5.0](https://github.com/facebook/react-native/commit/5f1d4312276c3b3f5e14abc3dac3fe31d46a5951) which means a new method `getEtras()` now needs to be implemented in `IconImageInfo`.

```
node_modules\@react-native-community\toolbar-android\android\src\main\java\com\reactnativecommunity\toolbarandroid\ReactToolbar.java:107: error: IconImageInfo is 
not abstract and does not override abstract method getExtras() in HasImageMetadata
  private static class IconImageInfo implements ImageInfo {
                 ^
```

[`ImageInfo` on fresco](https://github.com/facebook/fresco/blob/bbe21f260bba7057ddbe054de976c279e7a771f7/imagepipeline-base/src/main/java/com/facebook/imagepipeline/image/ImageInfo.java#L11)
[`HasImageMetadata` on fresco](https://github.com/facebook/fresco/blob/bbe21f260bba7057ddbe054de976c279e7a771f7/imagepipeline-base/src/main/java/com/facebook/imagepipeline/image/HasImageMetadata.java#L13)

**Comment by sikky99** [comment]
same error
