### ISSUE TITLE
IconImageInfo is not abstract and does not override abstract method getExtras() in HasImageMetadata

### ISSUE THREAD

**Issue by the-smart-home-maker** [react-native-toolbar-android/toolbar-android#57]
Hi there,

there seems to be a new problem that arose for me after upgrading to React Native 0.65.1. When I try to build my app on Android, I receive the following error:

```
IconImageInfo is not abstract and does not override abstract method getExtras() in HasImageMetadata
  private static class IconImageInfo implements ImageInfo {
```

For now, I was able to get over this error by adding the following lines to node_modules/@react-native-community/toolbar-android/android/src/main/java/com/reactnativecommunity/toolbarandroid/ReactToolbar.java.

Additional import statements at top of file:

```
...
import java.util.Map;
import java.util.HashMap;
...
```

Additional method added in class IconImageInfo:

```
public Map<String,Object> getExtras() { return new HashMap<String,Object>(); }
```

This lets me at least get around this error message. But it's a "dirty workaround" and it would be good to solve the issue within the package.

**Comment by jefferyjxn** [comment]
Thanks for this solution @the-smart-home-maker. I ran into the same issue after an RN upgrade. Agree it would be great to get a release that fixes this cleanly.

**Comment by SeanDunford** [comment]
Pretty sure this issue can be closed. 

@jefferyjxn and @the-smart-home-maker  I think you need to ensure that your local dependency for `react-native-toolbar` version is using the latest version. 

Left a more detailed comment here: https://github.com/react-native-toolbar-android/toolbar-android/pull/63

**Comment by the-smart-home-maker** [comment]
@SeanDunford yes, this can be closed. I can confirm that after running `yarn upgrade @react-native-community/toolbar-android@^0.2.1`, the problem is gone. Thank you!
